import torch

# Random
CUDA_AVAILABLE = True and torch.cuda.is_available()
USE_TENSORBOARD = True
TF_PATH = 'tensorboard'
EXPERIMENT_PATH_PREFIX = 'experiments/cvae'

# Model params
INITIAL_LEARNING_RATE = 0.001
LEARNING_RATE_UPDATE_CYCLES = 15000
HIDDEN_LAYERS = [400, 400, 400]
WEIGHT_DECAY = 0.0001
REPLAY_BUFFER_MAX_SIZE = 50000
BATCH_SIZE = 32
X_DIM = 2
C_DIM = 10
LATENT_DIM = 32





